#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Pages
app_electroneum_index:
    path: /
    controller: App\Controller\Pages\Index::show
    
app_electroneum_dashboard:
    path: /dashboard
    controller: App\Controller\Pages\Dashboard::show

# Authentication API
app_electroneum_api_auth_signin:
    path: /api/auth/signin
    controller: App\Controller\Api\Auth\SignIn::sign_in

app_electroneum_api_auth_signout:
    path: /api/auth/signout
    controller: App\Controller\Api\Auth\SignOut::sign_out

# User API
app_electroneum_api_user_closeacc:
    path: /api/user/closeacc
    controller: App\Controller\Api\User\CloseAcc::close_acc

app_electroneum_api_user_register:
    path: /api/user/register
    controller: App\Controller\Api\User\Register::register

app_electroneum_api_user_update:
    path: /api/user/update
    controller: App\Controller\Api\User\Update::update

# Styling
app_electroneum_web_css:
    path: /css/{css}
    controller: App\Controller\Pages\Rendering\Css::load
    
app_electroneum_web_fonts:
    path: /fonts/{fonts}
    controller: App\Controller\Pages\Rendering\Fonts::load
    
app_electroneum_web_img:
    path: /img/{img}
    controller: App\Controller\Pages\Rendering\Img::load_from_base_folder
    
app_electroneum_web_img_folder:
    path: /img/{img_folder}/{img}
    controller: App\Controller\Pages\Rendering\Img::load_with_folder
    
app_electroneum_web_js:
    path: /js/{js}
    controller: App\Controller\Pages\Rendering\Js::load
    